apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: qoves-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/judethegemini/qoves-api@sha256:edcffc7235af3349055e0665de64b38b323e973a2afef2433fe53d83d8d8fed3
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: api-db
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
